### ISSUE TITLE
Sky tooltip component contribution

### ISSUE THREAD

**Issue by blackbaud-conorwright** [blackbaud/skyux-indicators#100]
I made a skyux tooltip component to add tooltips to my buttons and such in the skyux rich text editor. Seems like a pretty generally useful thing, so I figured I'd contribute it. I don't care too much, so feel free to throw it out too.

**Comment by Blackbaud-TrevorBurch** [comment]
In consultation with design we decided this is not something we want to prioritize at this time and have decided to close this at this point.
