### ISSUE TITLE
Tokens demo - Using same tokens for all section

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux-indicators#119]
We are using the same tokens under the hood for the first four sections of the demo. This causes tokens in the non-dismissible section to disappear when they are dismissed in the first section and other similar interactions. We should look at simplifying things and using different tokens for the different sections to avoid confusion for consumers.

[AB#1548554](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1548554)

**Comment by Blackbaud-AlexKingman** [comment]
This is moot now that we've separated out the demos in the new version. This will be released shortly.
