### ISSUE TITLE
Update icon component with first class way to change colors

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux-indicators#45]
We had a request to update the docs with instructions for how to update the color of icons. We don't currently have a first-class way to do this. According to Steve:

`The only way to style the  sky-icon today is by adding color styles to any parent components/elements wrapping the sky-icon component. There is not a first-class way to style the icon. My suggestion was to create a new input on the sky-icon component that would accept a “type”, and we could provide the appropriate colors internally. This would require additional engineering.`

I'm not sure the priority of adding this option, but it seems like it would be better to put this on our backlog than to document a workaround.

**Comment by Blackbaud-SteveBrush** [comment]
Currently, we have a few CSS classes that demonstrate specific icons using specific SKY-themed, colors: https://developer.blackbaud.com/skyux/components/status-indicator. Are there any use cases beyond the ones provided on that page?

**Comment by blackbaud-johnly** [comment]
After researching use cases for this and the amount of work involved, we are closing this issue until a strong use case emerges. If that happens, we will reopen and revisit the issue.
