### ISSUE TITLE
sky-label not appearing correctly inside page-summary

### ISSUE THREAD

**Issue by Blackbaud-SuyashGupta** [blackbaud/skyux-indicators#71]
### Expected behavior 
There should be space between icon & text.
![image](https://user-images.githubusercontent.com/62419367/77144985-5370a880-6aad-11ea-81b3-198487737e9f.png)

### Actual behavior
There is no space between icon & text.
![tempsnip](https://user-images.githubusercontent.com/62419367/77145096-a0547f00-6aad-11ea-94cc-86e13b4e8635.png)

### Steps to reproduce
Use sky-label inside sky-page-summary-status. It can be seen directly in the [docs](https://developer.blackbaud.com/skyux/components/page-summary#demo).
### Severity
Medium
### Impact
Medium
### Type
Bug

**Comment by Blackbaud-SteveBrush** [comment]
Need to make sure the solution considers implementations that include their own whitespace characters and those that don't.
