### ISSUE TITLE
sky-alert in modern theme has odd visual artifacts/lines

### ISSUE THREAD

**Issue by jeffbdye** [blackbaud/skyux-indicators#98]
### Expected behavior
`sky-alert`'s icons do not have extra jagged lines.

### Actual behavior
Several lines appear off of the `sky-alert`.

### Steps to reproduce
https://developer.blackbaud.com/skyux-indicators/docs/alert;docs-active-tab=development
Windows 10, Chrome 83.0.4103.116 (Official Build) (64-bit) (cohort: Stable)
![image](https://user-images.githubusercontent.com/4132425/85904072-df454f80-b7d5-11ea-98ea-1a11661ad11e.png)
![image](https://user-images.githubusercontent.com/4132425/85904086-e4a29a00-b7d5-11ea-9bb2-02f30d04f9e0.png)
![image](https://user-images.githubusercontent.com/4132425/85904128-fc7a1e00-b7d5-11ea-8da1-1711d7f0ddae.png)

### Severity
Minor/visual

### Impact
Occurs in both the docs and in SPAs consuming the component.

**Comment by Blackbaud-PaulCrowder** [comment]
The issue seems related to this. It only happens in Windows with hardware acceleration turned on.

https://superuser.com/questions/1220106/weird-straight-lines-in-chrome-browser

**Comment by Blackbaud-PaulCrowder** [comment]
This is also isolated to the icons themselves, and is not related to SKY UX components. This simple HTML page displaying the custom icons also exhibits the issue. https://htmlpreview.github.io/?https://github.com/blackbaud/skyux-icons/blob/master/src/demo.html

**Comment by jeffbdye** [comment]
Right on, turns out I had that setting enabled. With it disabled, everything is as it should. Feel free to close the issue whenever y'all would like 👍

**Comment by Blackbaud-PaulCrowder** [comment]
Nah, we still need to address it because it's going to affect a significant number of users.

**Comment by Blackbaud-PaulCrowder** [comment]
This has been fixed in `@skyux/theme` version 4.3.0.
